"""
Reflective memory: accumulates insights from experiment comparisons.
Extended from v1 with code-change insight categories.
Inspired by MARS paper's Comparative Reflective Memory.
"""

import json
import os
import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import List, Optional


@dataclass
class Insight:
    id: str = ""
    observation: str = ""
    evidence: List[str] = field(default_factory=list)
    confidence: float = 0.5
    category: str = "general"  # architecture, hyperparameter, loss, training, augmentation, code_change
    parameter_affected: Optional[str] = None
    recommendation: str = ""
    created_at: str = ""
    last_updated: str = ""

    def __post_init__(self):
        if not self.id:
            self.id = str(uuid.uuid4())[:8]
        if not self.created_at:
            self.created_at = datetime.now().isoformat()
        if not self.last_updated:
            self.last_updated = self.created_at


BOOTSTRAP_INSIGHTS = [
    Insight(
        observation="Separate heads significantly outperform shared heads (0.656 vs 0.80+)",
        evidence=["separate_cloc_high_margin", "margin_2.0_1.5_1.0_0.5"],
        confidence=0.95,
        category="architecture",
        parameter_affected="model_type",
        recommendation="Always use model_type='separate'",
    ),
    Insight(
        observation="CLOC contrastive loss improves performance over baseline (0.656 vs 0.67)",
        evidence=["separate_cloc_high_margin", "separate_baseline"],
        confidence=0.8,
        category="loss",
        parameter_affected="use_cloc",
        recommendation="Keep use_cloc=True",
    ),
    Insight(
        observation="MSE+WK loss outperforms CE loss (0.656 vs 0.722)",
        evidence=["separate_cloc_high_margin", "separate_cloc_CE"],
        confidence=0.85,
        category="loss",
        parameter_affected="severity_loss_fn",
        recommendation="Use MSE+WK, not CE",
    ),
    Insight(
        observation="CLOC weight 0.3 and 0.5 perform equally well (both ~0.656)",
        evidence=["separate_cloc_high_margin", "separate_cloc_w0.3"],
        confidence=0.7,
        category="hyperparameter",
        parameter_affected="cloc_weight",
        recommendation="Explore values around 0.3-0.7",
    ),
    Insight(
        observation="Margins [2.0, 1.0, 0.8, 0.6] are best tested preset",
        evidence=["separate_cloc_high_margin"],
        confidence=0.6,
        category="hyperparameter",
        parameter_affected="initial_margins",
        recommendation="Explore variations around [2.0, 1.0, 0.8, 0.6]",
    ),
    Insight(
        observation="입_오 (mouth O) consistently has worst per-action MAE (~1.0)",
        evidence=["separate_cloc_high_margin", "separate_baseline"],
        confidence=0.9,
        category="general",
        recommendation="Focus optimization on improving 입_오 performance",
    ),
    Insight(
        observation="Hyperparameter tuning alone has plateaued around 0.63 MAE — code-level changes needed",
        evidence=["bootstrap_analysis"],
        confidence=0.7,
        category="general",
        recommendation="Try architecture changes, new loss functions, or augmentation strategies",
    ),
]


class ReflectiveMemory:
    def __init__(self, memory_path: str):
        self.memory_path = memory_path
        self.insights: List[Insight] = []
        self._load()

    def _load(self):
        if os.path.exists(self.memory_path):
            with open(self.memory_path) as f:
                data = json.load(f)
            self.insights = [Insight(**d) for d in data]

    def _save(self):
        os.makedirs(os.path.dirname(self.memory_path), exist_ok=True)
        with open(self.memory_path, "w") as f:
            json.dump([asdict(i) for i in self.insights], f,
                      indent=2, ensure_ascii=False)

    def bootstrap(self):
        if self.insights:
            return
        for insight in BOOTSTRAP_INSIGHTS:
            self.add_insight(insight)

    def add_insight(self, insight: Insight):
        existing = self._find_similar(insight)
        if existing:
            for eid in insight.evidence:
                if eid not in existing.evidence:
                    existing.evidence.append(eid)
            existing.confidence = min(0.95, existing.confidence + 0.1)
            existing.last_updated = datetime.now().isoformat()
        else:
            self.insights.append(insight)
        self._save()

    def add_insights_from_judge(self, judge_insights: list):
        """Add insights generated by the Judge agent."""
        for ji in judge_insights:
            if not isinstance(ji, dict):
                continue
            insight = Insight(
                observation=ji.get("observation", ""),
                confidence=ji.get("confidence", 0.5),
                category=ji.get("category", "general"),
                parameter_affected=ji.get("parameter_affected"),
                recommendation=ji.get("recommendation", ""),
            )
            if insight.observation:
                self.add_insight(insight)

    def get_insights(self, category: Optional[str] = None,
                     min_confidence: float = 0.0) -> List[Insight]:
        result = self.insights
        if category:
            result = [i for i in result if i.category == category]
        result = [i for i in result if i.confidence >= min_confidence]
        return sorted(result, key=lambda x: x.confidence, reverse=True)

    def format_for_llm(self) -> str:
        lines = []
        for insight in sorted(self.insights, key=lambda x: x.confidence, reverse=True):
            if insight.confidence >= 0.8:
                marker = "[HIGH]"
            elif insight.confidence >= 0.5:
                marker = "[MED]"
            else:
                marker = "[LOW]"
            lines.append(
                f"{marker} (conf={insight.confidence:.2f}, evidence={len(insight.evidence)}) "
                f"{insight.observation} -> {insight.recommendation}"
            )
        return "\n".join(lines) if lines else "No insights accumulated yet."

    def get_completed_techniques(self) -> List[str]:
        """Get list of techniques/approaches that have been tried."""
        techniques = []
        for insight in self.insights:
            if insight.category in ("architecture", "loss", "augmentation", "code_change"):
                techniques.append(insight.observation)
        return techniques

    def _find_similar(self, new_insight: Insight) -> Optional[Insight]:
        if not new_insight.parameter_affected:
            return None
        for insight in self.insights:
            if insight.parameter_affected == new_insight.parameter_affected:
                if insight.recommendation and new_insight.recommendation:
                    if insight.recommendation == new_insight.recommendation:
                        return insight
        return None
